apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp
  namespace: backend
  labels:
    app: yarp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yarp
  template:
    metadata:
      labels:
        app: yarp
    spec:
      containers:
        - name: yarp
          image: registry.hamdocker.ir/amir-cloud/yarp-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: APP_UID
              value: "1000"   
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - name: http
              containerPort: 8080
            - name: https-admin
              containerPort: 8081
          resources:
            requests:
              cpu: "512m"      
              memory: "512Mi"
          readinessProbe:
           httpGet:
             path: /health
             port: 8081
             scheme: HTTPS   
           periodSeconds: 30
           timeoutSeconds: 5
          livenessProbe:
           httpGet:
             path: /health
             port: 8081
             scheme: HTTPS   
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
