apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-front
  namespace: backend
  labels:
    app: yarp-front
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0   # do not take any ready pod down until a new one is ready
      maxSurge: 1         # add at most 1 extra pod during the rollout
  minReadySeconds: 10      
  progressDeadlineSeconds: 60  
  selector:
    matchLabels:
      app: yarp-front
  template:
    metadata:
      labels:
        app: yarp-front
    spec:
      containers:
        - name: web
          image: registry.hamdocker.ir/amir-cloud/yarp-front:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "500m"     
              memory: "512Mi" 
          
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3