apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-frontend
  namespace: backend
  labels:
    app: yarp-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0   
      maxSurge: 1         
  minReadySeconds: 10      
  progressDeadlineSeconds: 60  
  selector:
    matchLabels:
      app: yarp-frontend
  template:
    metadata:
      labels:
        app: yarp-frontend
    spec:
      containers:
        - name: yarp-frontend
          image: gitlab.amitis.local:5050/a.khazaei/yarp-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "500m"     
              memory: "512Mi" 
          
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3